sh build.sh lsexception
sh build.sh lsitem
sh build.sh lscopyitem
sh build.sh lsbuffer
sh build.sh lscstring
sh build.sh lsio
sh build.sh lstime
sh build.sh lsorderedmap
sh build.sh lsjson
sh build.sh lspool
sh build.sh lsepoll
sh build.sh lsnet
sh build.sh lshttp
sh build.sh lslogger
sh build.sh lsssl
