sh build.sh lssha256
sh build.sh lsexception
sh build.sh lstime
sh build.sh lslogger
sh build.sh lsitem
sh build.sh lscopyableitem
sh build.sh lsbuffer
sh build.sh lscstring
sh build.sh lsio
sh build.sh lsorderedmap
sh build.sh lsjson
sh build.sh lspool
sh build.sh lsepoll
sh build.sh lsnet
sh build.sh lshttp
sh build.sh lsssl
